backend:
  name: git-gateway
  branch: master 
locale: 'ja' #メッセージが日本語化
media_folder: "content/blog"
public_folder : "/media" 

publish_mode: edjitorial_workflow
collections:
  - name: "Blog" 
    label: "Blog"
    folder: "docs/Blog"
    create: true
    slug: "{{slug}}" #ファイル名になる
    editor:
    preview: true #CMSの編集画面にプレビューがつく
    fields:
      - {label: "Title", name: "title", widget: "string"} 
      - {label: "Body", name: "body", widget: "markdown"}
